name: Build Docker images

on:
  push:
    branches:
      - master
      - chonky-version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Publish Docker Image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ github.token }}
  build-chonky:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: chonky-version
    - name: Publish Docker Image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ github.token }}
        tag: chonky
